default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: recruiter_development

test:
  <<: *default
  database: recruiter_test

production:
  <<: *default
  database: recruiter_production
  username: root
  password: <%= ENV['RUBYJOBSBRAZIL_DATABASE_PASSWORD'] %>
